import { z } from 'zod';
declare const environmentSchema: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "production", "test"]>>;
    APP_PORT: z.ZodDefault<z.ZodNumber>;
    APP_HOST: z.ZodDefault<z.ZodString>;
    APP_NAME: z.ZodDefault<z.ZodString>;
    APP_VERSION: z.ZodDefault<z.ZodString>;
    LOG_LEVEL: z.ZodDefault<z.ZodEnum<["error", "warn", "info", "http", "debug"]>>;
    DATABASE_URL: z.ZodString;
    DATABASE_POOL_MIN: z.ZodDefault<z.ZodNumber>;
    DATABASE_POOL_MAX: z.ZodDefault<z.ZodNumber>;
    REDIS_HOST: z.ZodDefault<z.ZodString>;
    REDIS_PORT: z.ZodDefault<z.ZodNumber>;
    REDIS_PASSWORD: z.ZodOptional<z.ZodString>;
    REDIS_DB: z.ZodDefault<z.ZodNumber>;
    REDIS_URL: z.ZodOptional<z.ZodString>;
    OLLAMA_BASE_URL: z.ZodDefault<z.ZodString>;
    OLLAMA_STORY_MODEL: z.ZodDefault<z.ZodString>;
    OLLAMA_SEO_MODEL: z.ZodDefault<z.ZodString>;
    OLLAMA_TIMEOUT_MS: z.ZodDefault<z.ZodNumber>;
    OLLAMA_MAX_RETRIES: z.ZodDefault<z.ZodNumber>;
    COMFYUI_BASE_URL: z.ZodDefault<z.ZodString>;
    COMFYUI_TIMEOUT_MS: z.ZodDefault<z.ZodNumber>;
    COMFYUI_MAX_RETRIES: z.ZodDefault<z.ZodNumber>;
    PIPER_BINARY_PATH: z.ZodDefault<z.ZodString>;
    PIPER_MODEL_PATH: z.ZodDefault<z.ZodString>;
    PIPER_VOICE: z.ZodDefault<z.ZodString>;
    PIPER_SAMPLE_RATE: z.ZodDefault<z.ZodNumber>;
    WHISPER_MODEL: z.ZodDefault<z.ZodString>;
    WHISPER_LANGUAGE: z.ZodDefault<z.ZodString>;
    WHISPER_DEVICE: z.ZodDefault<z.ZodEnum<["cpu", "cuda"]>>;
    FFMPEG_BINARY_PATH: z.ZodDefault<z.ZodString>;
    FFPROBE_BINARY_PATH: z.ZodDefault<z.ZodString>;
    VIDEO_WIDTH: z.ZodDefault<z.ZodNumber>;
    VIDEO_HEIGHT: z.ZodDefault<z.ZodNumber>;
    VIDEO_FPS: z.ZodDefault<z.ZodNumber>;
    VIDEO_CODEC: z.ZodDefault<z.ZodString>;
    VIDEO_CRF: z.ZodDefault<z.ZodNumber>;
    AUDIO_CODEC: z.ZodDefault<z.ZodString>;
    AUDIO_BITRATE: z.ZodDefault<z.ZodString>;
    STORAGE_TYPE: z.ZodDefault<z.ZodEnum<["local", "s3"]>>;
    STORAGE_LOCAL_PATH: z.ZodDefault<z.ZodString>;
    S3_ENDPOINT: z.ZodOptional<z.ZodString>;
    S3_ACCESS_KEY_ID: z.ZodOptional<z.ZodString>;
    S3_SECRET_ACCESS_KEY: z.ZodOptional<z.ZodString>;
    S3_BUCKET: z.ZodOptional<z.ZodString>;
    S3_REGION: z.ZodOptional<z.ZodString>;
    S3_PUBLIC_URL: z.ZodOptional<z.ZodString>;
    QUEUE_CONCURRENCY: z.ZodDefault<z.ZodNumber>;
    QUEUE_MAX_RETRIES: z.ZodDefault<z.ZodNumber>;
    QUEUE_RETRY_DELAY_MS: z.ZodDefault<z.ZodNumber>;
    QUEUE_JOB_TIMEOUT_MS: z.ZodDefault<z.ZodNumber>;
    SCHEDULE_INTERVAL_HOURS: z.ZodDefault<z.ZodNumber>;
    SCHEDULE_ENABLED: z.ZodDefault<z.ZodBoolean>;
    SCHEDULE_TIMEZONE: z.ZodDefault<z.ZodString>;
    STORY_MAX_SCENES: z.ZodDefault<z.ZodNumber>;
    STORY_EPISODE_DURATION_SECONDS: z.ZodDefault<z.ZodNumber>;
    STORY_TARGET_AUDIENCE: z.ZodDefault<z.ZodString>;
    STORY_IMAGE_STYLE: z.ZodDefault<z.ZodString>;
    JWT_SECRET: z.ZodDefault<z.ZodString>;
    JWT_EXPIRES_IN: z.ZodDefault<z.ZodString>;
    JWT_REFRESH_EXPIRES_IN: z.ZodDefault<z.ZodString>;
    CORS_ORIGINS: z.ZodDefault<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    NODE_ENV: "production" | "development" | "test";
    LOG_LEVEL: "error" | "debug" | "info" | "warn" | "http";
    APP_PORT: number;
    APP_HOST: string;
    APP_NAME: string;
    APP_VERSION: string;
    DATABASE_URL: string;
    DATABASE_POOL_MIN: number;
    DATABASE_POOL_MAX: number;
    REDIS_HOST: string;
    REDIS_PORT: number;
    REDIS_DB: number;
    OLLAMA_BASE_URL: string;
    OLLAMA_STORY_MODEL: string;
    OLLAMA_SEO_MODEL: string;
    OLLAMA_TIMEOUT_MS: number;
    OLLAMA_MAX_RETRIES: number;
    COMFYUI_BASE_URL: string;
    COMFYUI_TIMEOUT_MS: number;
    COMFYUI_MAX_RETRIES: number;
    PIPER_BINARY_PATH: string;
    PIPER_MODEL_PATH: string;
    PIPER_VOICE: string;
    PIPER_SAMPLE_RATE: number;
    WHISPER_MODEL: string;
    WHISPER_LANGUAGE: string;
    WHISPER_DEVICE: "cpu" | "cuda";
    FFMPEG_BINARY_PATH: string;
    FFPROBE_BINARY_PATH: string;
    VIDEO_WIDTH: number;
    VIDEO_HEIGHT: number;
    VIDEO_FPS: number;
    VIDEO_CODEC: string;
    VIDEO_CRF: number;
    AUDIO_CODEC: string;
    AUDIO_BITRATE: string;
    STORAGE_TYPE: "local" | "s3";
    STORAGE_LOCAL_PATH: string;
    QUEUE_CONCURRENCY: number;
    QUEUE_MAX_RETRIES: number;
    QUEUE_RETRY_DELAY_MS: number;
    QUEUE_JOB_TIMEOUT_MS: number;
    SCHEDULE_INTERVAL_HOURS: number;
    SCHEDULE_ENABLED: boolean;
    SCHEDULE_TIMEZONE: string;
    STORY_MAX_SCENES: number;
    STORY_EPISODE_DURATION_SECONDS: number;
    STORY_TARGET_AUDIENCE: string;
    STORY_IMAGE_STYLE: string;
    JWT_SECRET: string;
    JWT_EXPIRES_IN: string;
    JWT_REFRESH_EXPIRES_IN: string;
    CORS_ORIGINS: string;
    REDIS_PASSWORD?: string | undefined;
    REDIS_URL?: string | undefined;
    S3_ENDPOINT?: string | undefined;
    S3_ACCESS_KEY_ID?: string | undefined;
    S3_SECRET_ACCESS_KEY?: string | undefined;
    S3_BUCKET?: string | undefined;
    S3_REGION?: string | undefined;
    S3_PUBLIC_URL?: string | undefined;
}, {
    DATABASE_URL: string;
    NODE_ENV?: "production" | "development" | "test" | undefined;
    LOG_LEVEL?: "error" | "debug" | "info" | "warn" | "http" | undefined;
    APP_PORT?: number | undefined;
    APP_HOST?: string | undefined;
    APP_NAME?: string | undefined;
    APP_VERSION?: string | undefined;
    DATABASE_POOL_MIN?: number | undefined;
    DATABASE_POOL_MAX?: number | undefined;
    REDIS_HOST?: string | undefined;
    REDIS_PORT?: number | undefined;
    REDIS_PASSWORD?: string | undefined;
    REDIS_DB?: number | undefined;
    REDIS_URL?: string | undefined;
    OLLAMA_BASE_URL?: string | undefined;
    OLLAMA_STORY_MODEL?: string | undefined;
    OLLAMA_SEO_MODEL?: string | undefined;
    OLLAMA_TIMEOUT_MS?: number | undefined;
    OLLAMA_MAX_RETRIES?: number | undefined;
    COMFYUI_BASE_URL?: string | undefined;
    COMFYUI_TIMEOUT_MS?: number | undefined;
    COMFYUI_MAX_RETRIES?: number | undefined;
    PIPER_BINARY_PATH?: string | undefined;
    PIPER_MODEL_PATH?: string | undefined;
    PIPER_VOICE?: string | undefined;
    PIPER_SAMPLE_RATE?: number | undefined;
    WHISPER_MODEL?: string | undefined;
    WHISPER_LANGUAGE?: string | undefined;
    WHISPER_DEVICE?: "cpu" | "cuda" | undefined;
    FFMPEG_BINARY_PATH?: string | undefined;
    FFPROBE_BINARY_PATH?: string | undefined;
    VIDEO_WIDTH?: number | undefined;
    VIDEO_HEIGHT?: number | undefined;
    VIDEO_FPS?: number | undefined;
    VIDEO_CODEC?: string | undefined;
    VIDEO_CRF?: number | undefined;
    AUDIO_CODEC?: string | undefined;
    AUDIO_BITRATE?: string | undefined;
    STORAGE_TYPE?: "local" | "s3" | undefined;
    STORAGE_LOCAL_PATH?: string | undefined;
    S3_ENDPOINT?: string | undefined;
    S3_ACCESS_KEY_ID?: string | undefined;
    S3_SECRET_ACCESS_KEY?: string | undefined;
    S3_BUCKET?: string | undefined;
    S3_REGION?: string | undefined;
    S3_PUBLIC_URL?: string | undefined;
    QUEUE_CONCURRENCY?: number | undefined;
    QUEUE_MAX_RETRIES?: number | undefined;
    QUEUE_RETRY_DELAY_MS?: number | undefined;
    QUEUE_JOB_TIMEOUT_MS?: number | undefined;
    SCHEDULE_INTERVAL_HOURS?: number | undefined;
    SCHEDULE_ENABLED?: boolean | undefined;
    SCHEDULE_TIMEZONE?: string | undefined;
    STORY_MAX_SCENES?: number | undefined;
    STORY_EPISODE_DURATION_SECONDS?: number | undefined;
    STORY_TARGET_AUDIENCE?: string | undefined;
    STORY_IMAGE_STYLE?: string | undefined;
    JWT_SECRET?: string | undefined;
    JWT_EXPIRES_IN?: string | undefined;
    JWT_REFRESH_EXPIRES_IN?: string | undefined;
    CORS_ORIGINS?: string | undefined;
}>;
export type Environment = z.infer<typeof environmentSchema>;
export declare function getEnv(): Environment;
export declare function resetEnvCache(): void;
export {};
//# sourceMappingURL=config.d.ts.map